document.documentElement.classList.add('js');
const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
const projectData={"forma":{"title": "Taxi booking & driver apps", "type": "Smartzi Lanka / UI/UX design", "intro": "Interface design work at Smartzi Lanka across B2B taxi booking, driver applications and websites.", "problem": "Design clear interfaces for the different people using booking and driver products.", "approach": "Collaborated with developers and stakeholders to shape interfaces around user and market needs.", "details": "B2B taxi booking · Driver applications · Web design", "next": "UI/UX Designer from April 2023, following an Associate UI/UX Designer role from March 2022 to April 2023."},"still":{"title": "Design for food ordering", "type": "Cookoo / Graphic consulting", "intro": "Graphic consulting for a Sri Lankan food-ordering platform.", "problem": "Support the design team with consistent visual decisions across product graphics and production formats.", "approach": "Advised on style, format and print production, and contributed product illustrations, logos, app graphics and layouts.", "details": "Visual direction · Illustration · Logos · App graphics · Layouts", "next": "Graphic Consultant · 2019–2020."},"index":{"title": "Communicating cybersecurity", "type": "Cyberarch / Graphic design", "intro": "Marketing design for a cybersecurity consulting business offering information security and forensics services.", "problem": "Communicate technical services through clear, engaging visual material.", "approach": "Created marketing materials and visual concepts to support the company’s services.", "details": "Marketing materials · Visual concepts · Cybersecurity communication", "next": "Graphic Designer · 2016–2017."},after:{title:'Day & Night',type:'Thuvarakan / Personal portfolio',intro:'A shop, by day and by night, for a lifelong entrepreneurial ambition. This portfolio brings my career and the dream of building something of my own into the same space.',problem:'How do graphic design, UI design, development, design consulting, UI UX engineering and my current QA role fit into one personal story?',approach:'The store is the connecting idea. I welcome visitors at the door, share the six chapters of my career, and use the shelves and receipt to show what I carry forward.',details:'Personal narrative · Storefront concept · Scroll-driven introduction',next:'Keep adding real work and new chapters as my career develops.'}};
const dialog=document.querySelector('#project-dialog');
document.querySelectorAll('[data-project]').forEach(el=>el.addEventListener('click',()=>{const d=projectData[el.dataset.project];dialog.querySelector('.dialog-content').innerHTML=`<div class="eyebrow">${d.type}</div><h2>${d.title}</h2><p>${d.intro}</p><div class="dialog-grid"><div><h3>The question</h3><p>${d.problem}</p></div><div><h3>The direction</h3><p>${d.approach}</p></div></div><h3>Scope</h3><p>${d.details}</p><h3>${el.dataset.project==='after'?'Next step':'Role & period'}</h3><p>${d.next}</p><p class="contact-note">${el.dataset.project==='after'?'The story behind this personal portfolio.':'Work overview based on my résumé.'}</p>`;dialog.showModal()}));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
document.querySelectorAll('[data-receipt]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#receipt-dialog').showModal()));
document.querySelectorAll('[data-motion]').forEach(b=>b.addEventListener('click',()=>{const paused=document.body.classList.toggle('paused');b.textContent=paused?'Motion: off':'Motion: on';b.setAttribute('aria-pressed',String(paused))}));
const clock=document.querySelector('[data-clock]');if(clock){const tick=()=>{clock.textContent=new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())};tick();setInterval(tick,60000)}
const ring=document.querySelector('[data-ring]');if(ring)ring.addEventListener('click',()=>{ring.textContent='Ding! You have my attention.';document.querySelector('#contact').scrollIntoView({behavior:document.body.classList.contains('paused')?'instant':'smooth'})});

// The native disclosures also work without JavaScript.
const careerShelves=[...document.querySelectorAll('.experience-shelf')];
careerShelves.forEach(shelf=>shelf.addEventListener('toggle',()=>{
 if(!shelf.open){
  if(!careerShelves.some(item=>item.open)){
   document.querySelector('[data-inventory-count]').textContent='—';
   document.querySelector('[data-inventory-skill]').textContent='Choose a shelf';
  }
  return;
 }
 careerShelves.forEach(other=>{if(other!==shelf)other.open=false});
 document.querySelector('[data-inventory-count]').textContent=shelf.dataset.shelf;
 document.querySelector('[data-inventory-skill]').textContent=shelf.dataset.takeaway;
}));
